DEBUG 2021-01-18 17:36:44.937 UTC: 	 CRAB Client version: v3.201110
DEBUG 2021-01-18 17:36:44.937 UTC: 	 Running on: Linux lxplus724.cern.ch 3.10.0-1160.2.2.el7.x86_64 #1 SMP Tue Oct 20 16:53:08 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2021-01-18 17:36:44.937 UTC: 	 Executing command: 'status'
DEBUG 2021-01-18 17:36:44.937 UTC: 	 Found CRAB cache file /afs/cern.ch/user/g/gkaratha/.crab3
ERROR 2021-01-18 17:36:44.938 UTC: 	 Error: L1Tracker_2021Jan18/crab_data_TTbar_PU140/ is not a valid CRAB project directory.
ERROR 2021-01-18 17:36:44.939 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/bin/crab", line 165, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/bin/crab", line 150, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/lib/CRABClient/Commands/status.py", line 41, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/lib/CRABClient/Commands/SubCommand.py", line 271, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/lib/CRABClient/Commands/SubCommand.py", line 628, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: L1Tracker_2021Jan18/crab_data_TTbar_PU140/ is not a valid CRAB project directory.
INFO 2021-01-18 17:36:44.941 UTC: 	 Log file is /afs/cern.ch/work/g/gkaratha/private/L1TrackTrigger/CMSSW_11_1_6/src/L1Trigger/L1TJetTrackAnalyzer/plotter/PlottingCore/EvtByEvt_test/crab.log
